/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.rgonzalez.afp.ui.simulacion;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

public class AfpUiSimulacionPanel extends javax.swing.JPanel {

    public AfpUiSimulacionPanel() {
        initComponents();
    }

    public JButton getButtonCalcular() {
        return buttonCalcular;
    }

    public JComboBox getComboAfp() {
        return comboAfp;
    }

    public JComboBox getComboFondo() {
        return comboFondo;
    }

    public JComboBox getComboPeriodoFin() {
        return comboPeriodoFin;
    }

    public JComboBox getComboPeriodoInicio() {
        return comboPeriodoInicio;
    }

    public JTable getTable() {
        return table;
    }

    public JTextField getTextCotizacion() {
        return textCotizacion;
    }

    public JTextField getTextTasaFija() {
        return textTasaFija;
    }

    public JPanel getPanelPlot() {
        return panelPlot;
    }

    public JButton getButtonPaginationNext() {
        return buttonPaginationNext;
    }

    public JButton getButtonPaginationPrev() {
        return buttonPaginationPrev;
    }

    public JComboBox getComboPagination() {
        return comboPagination;
    }

    public JPanel getPanelTableButtons() {
        return panelTableButtons;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelButtons = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboAfp = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboFondo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboPeriodoInicio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comboPeriodoFin = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        textCotizacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textTasaFija = new javax.swing.JTextField();
        buttonCalcular = new javax.swing.JButton();
        split = new javax.swing.JSplitPane();
        panelPlotArea = new javax.swing.JPanel();
        panelPlot = new javax.swing.JPanel();
        panelPlotButtons = new javax.swing.JPanel();
        buttonPaginationPrev = new javax.swing.JButton();
        comboPagination = new javax.swing.JComboBox();
        buttonPaginationNext = new javax.swing.JButton();
        panelTableArea = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panelTableButtons = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Simulacion");
        panelTitle.add(jLabel7);

        add(panelTitle, java.awt.BorderLayout.NORTH);

        panelMain.setLayout(new java.awt.BorderLayout());

        panelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("AFP");
        panelButtons.add(jLabel2);

        comboAfp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelButtons.add(comboAfp);

        jLabel4.setText("Fondo");
        panelButtons.add(jLabel4);

        comboFondo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelButtons.add(comboFondo);

        jLabel1.setText("Periodo");
        panelButtons.add(jLabel1);

        comboPeriodoInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelButtons.add(comboPeriodoInicio);

        jLabel3.setText("-");
        panelButtons.add(jLabel3);

        comboPeriodoFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelButtons.add(comboPeriodoFin);

        jLabel5.setText("Cotizacion");
        panelButtons.add(jLabel5);

        textCotizacion.setColumns(6);
        textCotizacion.setText("30000");
        panelButtons.add(textCotizacion);

        jLabel6.setText("Tasa Fija");
        panelButtons.add(jLabel6);

        textTasaFija.setColumns(6);
        textTasaFija.setText("0,002");
        panelButtons.add(textTasaFija);

        buttonCalcular.setText("Calcular"); // NOI18N
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });
        panelButtons.add(buttonCalcular);

        panelMain.add(panelButtons, java.awt.BorderLayout.PAGE_START);

        split.setDividerLocation(320);
        split.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelPlotArea.setLayout(new java.awt.BorderLayout());

        panelPlot.setLayout(new javax.swing.BoxLayout(panelPlot, javax.swing.BoxLayout.LINE_AXIS));
        panelPlotArea.add(panelPlot, java.awt.BorderLayout.CENTER);

        buttonPaginationPrev.setText("<");
        panelPlotButtons.add(buttonPaginationPrev);

        comboPagination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelPlotButtons.add(comboPagination);

        buttonPaginationNext.setText(">");
        panelPlotButtons.add(buttonPaginationNext);

        panelPlotArea.add(panelPlotButtons, java.awt.BorderLayout.SOUTH);

        split.setLeftComponent(panelPlotArea);

        panelTableArea.setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTable.setViewportView(table);

        panelTableArea.add(scrollTable, java.awt.BorderLayout.CENTER);

        panelTableButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        panelTableArea.add(panelTableButtons, java.awt.BorderLayout.SOUTH);

        split.setRightComponent(panelTableArea);

        panelMain.add(split, java.awt.BorderLayout.CENTER);

        add(panelMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed
    }//GEN-LAST:event_buttonCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JButton buttonPaginationNext;
    private javax.swing.JButton buttonPaginationPrev;
    private javax.swing.JComboBox comboAfp;
    private javax.swing.JComboBox comboFondo;
    private javax.swing.JComboBox comboPagination;
    private javax.swing.JComboBox comboPeriodoFin;
    private javax.swing.JComboBox comboPeriodoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPlot;
    private javax.swing.JPanel panelPlotArea;
    private javax.swing.JPanel panelPlotButtons;
    private javax.swing.JPanel panelTableArea;
    private javax.swing.JPanel panelTableButtons;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JSplitPane split;
    private javax.swing.JTable table;
    private javax.swing.JTextField textCotizacion;
    private javax.swing.JTextField textTasaFija;
    // End of variables declaration//GEN-END:variables
}
